---
- name: Provision all monitor nodes
  hosts: monitor
  become: true
  roles:
    - monitor

- name: Provision all MySQL nodes
  hosts:
    - mysql57
    - mysql8
    - mysql84
    - backup
    - restore
  become: true
  roles:
    - mysql_install

- name: Configure replication on all MySQL nodes
  hosts:
    - mysql57
    - mysql8
    - mysql84
    - backup
  become: true
  roles:
    - replication

- name: Provision all backup nodes
  hosts: backup
  become: true
  roles:
    - backup

- name: Provision all restore nodes
  hosts: restore
  become: true
  roles:
    - restore

- name: Provision all ProxySQL nodes
  hosts: proxysql
  become: true
  roles:
    - proxysql