---
- name: Provision all monitor nodes
  hosts: monitor
  become: true
  roles:
    - monitor
    
- name: Provision all MySQL nodes
  hosts: mysql57
  become: true
  roles:
    - mysql_install

- name: Configure replication on mysql8
  hosts: mysql8
  become: true
  roles:
    - mysql_install
    - replication

- name: Configure replication on mysql84
  hosts: mysql84
  become: true
  roles:
    - mysql_install
    - replication

- name: Provision all backup nodes
  hosts: backup
  become: true
  roles:
    - backup

- name: Provision all restore nodes
  hosts: restore
  become: true
  roles:
    - restore

- name: Provision all ProxySQL nodes
  hosts: proxysql
  become: true
  roles:
    - proxysql


