---
- name: Provision all monitor nodes
  hosts: monitors
  become: true
  roles:
    - monitor

- name: Provision all MySQL nodes
  hosts:
    - mysqls57
    - mysqls8
    - mysqls84
    - backups
    - restores
  become: true
  roles:
    - mysql_install

- name: Configure replication on all MySQL nodes
  hosts:
    - mysqls57
    - mysqls8
    - mysqls84
    - backups
  become: true
  roles:
    - replication

- name: Provision all backup nodes
  hosts: backups
  become: true
  roles:
    - backup

- name: Provision all restore nodes
  hosts: restores
  become: true
  roles:
    - restore

- name: Adding restore public keys to backup nodes
  hosts: backups
  become: true
  roles:
    - collect_restore_pubkeys

- name: Provision all ProxySQL nodes
  hosts: proxysqls
  become: true
  roles:
    - proxysql