SET sql_log_bin = 0;
-- Create percona user with full grants and grant option for all hosts
CREATE USER IF NOT EXISTS 'percona'@'%' IDENTIFIED BY 'Percona1234';
GRANT ALL PRIVILEGES ON *.* TO 'percona'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;
-- Create percona user for pmm-client 
CREATE USER IF NOT EXISTS 'percona'@'localhost' IDENTIFIED BY 'Percona1234';
GRANT ALL PRIVILEGES ON *.* TO 'percona'@'localhost' WITH GRANT OPTION;
ALTER USER 'percona'@'localhost' WITH MAX_USER_CONNECTIONS 10;
CREATE USER IF NOT EXISTS 'percona'@'127.0.0.1' IDENTIFIED BY 'Percona1234';
GRANT ALL PRIVILEGES ON *.* TO 'percona'@'127.0.0.1' WITH GRANT OPTION;
ALTER USER 'percona'@'127.0.0.1' WITH MAX_USER_CONNECTIONS 10;
-- Create percon user for proxysql hosts
CREATE USER IF NOT EXISTS 'percona'@'192.168.56.101' IDENTIFIED BY 'Percona1234';
GRANT ALL PRIVILEGES ON *.* TO 'percona'@'192.168.56.101' WITH GRANT OPTION;
ALTER USER 'percona'@'192.168.56.101' WITH MAX_USER_CONNECTIONS 2;
CREATE USER IF NOT EXISTS 'percona'@'192.168.56.102' IDENTIFIED BY 'Percona1234';
GRANT ALL PRIVILEGES ON *.* TO 'percona'@'192.168.56.102' WITH GRANT OPTION;
ALTER USER 'percona'@'192.168.56.102' WITH MAX_USER_CONNECTIONS 2;