---
# tasks file for replication

- name: Stop replication if running
  community.mysql.mysql_replication:
    mode: stopslave
    login_user: percona
    login_password: Percona1234
  failed_when: false
  when: replication_source_host is defined

- name: Configure replication for MySQL 8.4 (CHANGE REPLICATION SOURCE TO)
  community.mysql.mysql_query:
    login_user: percona
    login_password: Percona1234
    query: >
      CHANGE REPLICATION SOURCE TO
      SOURCE_HOST='{{ replication_source_host }}',
      SOURCE_USER='percona',
      SOURCE_PASSWORD='Percona1234',
      SOURCE_AUTO_POSITION=1
  when:
    - replication_source_host is defined
    - mysql84 in group_names

- name: Configure replication for other MySQL versions (CHANGE MASTER TO)
  community.mysql.mysql_replication:
    mode: changemaster
    master_host: "{{ replication_source_host }}"
    master_user: percona
    master_password: Percona1234
    master_auto_position: true
    login_user: percona
    login_password: Percona1234
  when:
    - replication_source_host is defined
    - mysql84 not in group_names

- name: Start replication for MySQL 8.4 (START REPLICA)
  community.mysql.mysql_query:
    login_user: percona
    login_password: Percona1234
    query: START REPLICA;
  when:
    - replication_source_host is defined
    - mysql84 in group_names

- name: Start replication for other MySQL versions (START SLAVE)
  community.mysql.mysql_replication:
    mode: startslave
    login_user: percona
    login_password: Percona1234
  when:
    - replication_source_host is defined
    - mysql84 not in group_names 