---
# tasks file for mysql_install
# TODO: Implement MySQL installation and configuration tasks

- name: Ensure required apt packages are installed
  ansible.builtin.apt:
    name:
      - gnupg2
      - wget
      - lsb-release
      - python3-pymysql
    state: present
    update_cache: true

- name: Download Percona release package
  ansible.builtin.get_url:
    url: "https://repo.percona.com/apt/percona-release_latest.{{ ansible_lsb.codename }}_all.deb"
    dest: /tmp/percona-release_latest_{{ ansible_lsb.codename }}_all.deb
    mode: '0644'

- name: Install Percona release package
  ansible.builtin.apt:
    deb: /tmp/percona-release_latest_{{ ansible_lsb.codename }}_all.deb
    state: present

- name: Enable Percona repo for correct version
  ansible.builtin.command: >
    percona-release enable-only {{ mysql_percona_repo }}
  args:
    creates: "/etc/apt/sources.list.d/percona-{{ mysql_percona_repo }}.list"

- name: Update apt cache after enabling repo
  ansible.builtin.apt:
    update_cache: true

- name: Install Percona Server
  ansible.builtin.apt:
    name: "{{ mysql_server_package }}"
    state: present
    update_cache: true

- name: Ensure percona user exists
  ansible.builtin.user:
    name: percona
    shell: /bin/bash
    state: present
    create_home: true

- name: Ensure percona user has passwordless sudo
  ansible.builtin.copy:
    dest: /etc/sudoers.d/percona
    content: 'percona ALL=(ALL) NOPASSWD:ALL'
    mode: '0440'
    owner: root
    group: root

- name: Copy .vagrant_profile to vagrant user
  ansible.builtin.copy:
    src: /vagrant/provision/.vagrant_profile
    dest: /home/vagrant/.profile
    owner: vagrant
    group: vagrant
    mode: '0644'

- name: Create .my.cnf for percona user
  ansible.builtin.copy:
    dest: /home/percona/.my.cnf
    content: |
      [client]
      user=percona
      password=Percona1234
      host=localhost
      prompt="{{ inventory_hostname }}> "
    owner: percona
    group: percona
    mode: '0600'

- name: Set up SSH authorized_keys for percona user
  ansible.posix.authorized_key:
    user: percona
    state: present
    key: "{{ lookup('file', '/vagrant/provision/monitor_id_rsa.pub') }}"
  when: lookup('file', '/vagrant/provision/monitor_id_rsa.pub', errors='ignore') is not none

- name: Copy custom MySQL config
  ansible.builtin.copy:
    src: "/vagrant//config/{{ mysql_config_file }}"
    dest: /etc/mysql/my.cnf
    owner: mysql
    group: mysql
    mode: '0644'

- name: Restart MySQL service
  ansible.builtin.service:
    name: mysql
    state: restarted

- name: Wait for MySQL to be ready
  ansible.builtin.command: "mysqladmin ping --silent"
  register: mysql_ping
  retries: 10
  delay: 2
  until: mysql_ping.rc == 0

- name: Import replication and monitoring users
  community.mysql.mysql_db:
    name: mysql
    state: import
    target: /vagrant/provision/mysql_users.sql
